# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 097fcecdb09d72722837be5e748c671574c37e83cf2e9e70bc661b6812cae8e96b8ab935e22416ac35367007dbead8cb63ee56590971d15a1daf20af826bfd87

test:
  secret_key_base: 30ba66091928fd38af7bea2ceb80c72d79580ea4b662c3476013f74c497744d51c460e91cedd85a04685d8152d0f8f3f9e8fcd4a9a78d5096e90c6b0aa126ec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
